logs: copy from journalctl to repo

diff --git a/templates/publish-metrics-github.sh.j2 b/templates/publish-metrics-github.sh.j2
--- a/templates/publish-metrics-github.sh.j2
+++ b/templates/publish-metrics-github.sh.j2
@@ -16,11 +16,6 @@ BENCHMARKING_SERVICE_LOG_FILE_NAME="{{ nimbus_eth1_service_log_output_name }}"
 BENCHMARKING_SERVICE_OUTPUT_LOG_FILE="{{ nimbus_eth1_benchmark_log_output_file_path }}"
 NIMBUS_ETH1_BLOCKS_IMPORT_SCRIPT_PATH="{{ nimbus_eth1_blocks_import_script_path }}"
 
-
-function log() {
-   echo "$(date '+%Y-%m-%d %H:%M:%S') - $*"
-}
-
 function convert_to_human_readable() {
   local total_ns=$1
 
@@ -29,10 +24,10 @@ function convert_to_human_readable() {
 
   # Convert to integer seconds for calculations
   local seconds_int=${total_seconds%.*}
-  local days=$(( seconds_int / 86400 ))
-  local hours=$(( (seconds_int % 86400) / 3600 ))
-  local minutes=$(( (seconds_int % 3600) / 60 ))
-  local seconds=$(( seconds_int % 60 ))
+  local days=$((seconds_int / 86400))
+  local hours=$(((seconds_int % 86400) / 3600))
+  local minutes=$(((seconds_int % 3600) / 60))
+  local seconds=$((seconds_int % 60))
 
   # For printing in human readable string
   local result=""
@@ -48,9 +43,10 @@ function convert_to_human_readable() {
   echo "$result"
 }
 
-function fetchBenchmarkingJobSummary () {
+function fetchBenchmarkingJobSummary() {
   local total_time
-  total_time=$(awk -F',' '
+  total_time=$(
+    awk -F',' '
       NR>1 { # Skip header row
           sum += $6
       }
@@ -60,8 +56,8 @@ function fetchBenchmarkingJobSummary () {
   )
 
   if [ -z "$total_time" ]; then
-      log "Error: No data found or invalid input"
-      exit 1
+    echo "Error: No time data found in csv or invalid input at $BENCHMARKING_FILE_PATH"
+    exit 1
   fi
 
   echo "=== Nimbus-ETH1 Benchmarking Report ==="
@@ -75,25 +71,25 @@ function fetchBenchmarkingJobSummary () {
   END_BLOCK_NUMBER=$(tail -1 "${BENCHMARKING_FILE_PATH}" | cut -d',' -f1)
   echo ">>> End block number is ${END_BLOCK_NUMBER}"
 
-  BENCHMARK_RUN_COMMAND=$(systemctl cat nimbus-eth1-mainnet-master-short-benchmark.service | sed -n '/^ExecStart=/,/[^\\]$/p' | sed 's/^ExecStart=//')
+  BENCHMARK_RUN_COMMAND=$(systemctl cat nimbus-eth1-mainnet-master-"${BENCHMARKING_TYPE}"-benchmark.service | sed -n '/^ExecStart=/,/[^\\]$/p' | sed 's/^ExecStart=//')
   echo ">>> Benchmarking was run using ${BENCHMARK_RUN_COMMAND}"
   echo "=========================="
 }
 
 function moveBenchmarkingFileToRepo() {
-  log ">>> starting moveBenchmarkingFileToRepo() inside publish-metrics-github.sh"
+  echo ">>> starting moveBenchmarkingFileToRepo() inside publish-metrics-github.sh"
 
-  log ">>> creating directory ${BENCHMARK_DESTINATION}"
+  echo ">>> mkdir -p ${BENCHMARK_DESTINATION}"
   mkdir -p "${BENCHMARK_DESTINATION}"
 
-  log ">>> copying debug-csv generated by nimbus to benchmarks repo"
-  log "cp ${BENCHMARKING_FILE_PATH} ${BENCHMARK_DESTINATION}/${BENCHMARK_FILE_NAME}"
+  echo ">>> copying debug-csv generated by nimbus to benchmarks repo"
+  echo "cp ${BENCHMARKING_FILE_PATH} ${BENCHMARK_DESTINATION}/${BENCHMARK_FILE_NAME}"
   cp "${BENCHMARKING_FILE_PATH}" "${BENCHMARK_DESTINATION}/${BENCHMARK_FILE_NAME}"
 
-  log ">>> completed moveBenchmarkingFileToRepo()"
+  echo ">>> completed moveBenchmarkingFileToRepo()"
 }
 
-function fetchHostInformation () {
+function fetchHostInformation() {
   echo "=== System Information Report ==="
   echo ">>> Generated on: $(date)"
   echo "=========================="
@@ -129,19 +125,19 @@ function fetchHostInformation () {
 }
 
 function compareBenchmarkWithPrevious() {
-  log "=== Comparison of last two benchmarks ==="
+  echo "=== Comparison of last two benchmarks ==="
 
   VENV_PATH="${NIMBUS_ETH1_GIT_REPO}/stats"
 
   CURRENT_BENCHMARK_TYPE_DIR="${BENCHMARK_GIT_REPO}/${BENCHMARKING_TYPE}-benchmark"
 
   if [ ! -d "${CURRENT_BENCHMARK_TYPE_DIR}" ]; then
-    log "${CURRENT_BENCHMARK_TYPE_DIR} does not exist, skipping compareBenchmarkWithPrevious()"
+    echo "${CURRENT_BENCHMARK_TYPE_DIR} does not exist, skipping compareBenchmarkWithPrevious()"
     return
   fi
 
   if [[ ! "$(find "${CURRENT_BENCHMARK_TYPE_DIR}" -mindepth 1 -maxdepth 1 -type d | wc -l)" -gt 2 ]]; then
-    log "${CURRENT_BENCHMARK_TYPE_DIR} does not contain 2 or more benchmark CSVs, skipping compareBenchmarkWithPrevious()"
+    echo "${CURRENT_BENCHMARK_TYPE_DIR} does not contain 2 or more benchmark CSVs, skipping compareBenchmarkWithPrevious()"
     return
   fi
 
@@ -152,58 +148,59 @@ function compareBenchmarkWithPrevious() {
   PREVIOUS_BENCHMARK_CSV_PATH="${CURRENT_BENCHMARK_TYPE_DIR}/${PREVIOUS_BENCHMARK_DIR_NAME}/${BENCHMARK_FILE_NAME}"
 
   if [ ! -d "${VENV_PATH}" ]; then
+    echo "python -m venv ${VENV_PATH}"
     python -m venv "${VENV_PATH}"
   fi
 
   # Activate virtual environment
+  echo "source ${VENV_PATH}/bin/activate"
   source "${VENV_PATH}/bin/activate"
 
   if [ -f "${NIMBUS_ETH1_GIT_REPO}/scripts/requirements.txt" ]; then
-    pip install -r "${NIMBUS_ETH1_GIT_REPO}/scripts/requirements.txt" > /dev/null 2>&1
+    echo "pip install -r ${NIMBUS_ETH1_GIT_REPO}/scripts/requirements.txt >/dev/null 2>&1"
+    pip install -r "${NIMBUS_ETH1_GIT_REPO}/scripts/requirements.txt" >/dev/null 2>&1
   fi
 
-  log "python ${NIMBUS_ETH1_BLOCKS_IMPORT_SCRIPT_PATH} ${CURRENT_BENCHMARK_CSV_PATH} ${PREVIOUS_BENCHMARK_CSV_PATH} 2>&1 || true"
+  echo "python ${NIMBUS_ETH1_BLOCKS_IMPORT_SCRIPT_PATH} ${CURRENT_BENCHMARK_CSV_PATH} ${PREVIOUS_BENCHMARK_CSV_PATH} 2>&1 || true"
 
   python "${NIMBUS_ETH1_BLOCKS_IMPORT_SCRIPT_PATH}" "${CURRENT_BENCHMARK_CSV_PATH}" "${PREVIOUS_BENCHMARK_CSV_PATH}" 2>&1 || true
 
   # Deactivate virtual environment
+  echo "deactivate"
   deactivate
 
-  log "=========================="
+  echo "=========================="
 }
 
 function moveServiceLogToRepo() {
-  # we intentionally log before we execute because we want these 4 commands to be part of the logs before we reset them
-  log ">>> copying import systemd service log file to benchmarks repo"
-  log "cp ${BENCHMARKING_SERVICE_OUTPUT_LOG_FILE} ${BENCHMARK_DESTINATION}/${BENCHMARKING_SERVICE_LOG_FILE_NAME}"
-  log ">>> truncating import systemd service log file"
-  log "cat /dev/null > ${BENCHMARKING_SERVICE_OUTPUT_LOG_FILE}"
 
-  cp "${BENCHMARKING_SERVICE_OUTPUT_LOG_FILE}" "${BENCHMARK_DESTINATION}/${BENCHMARKING_SERVICE_LOG_FILE_NAME}"
-  # we can't delete this file since its needed for next runs
-  cat /dev/null > "${BENCHMARKING_SERVICE_OUTPUT_LOG_FILE}"
+  SYSTEMD_INVOCATION_ID=$(systemctl show --value -p InvocationID nimbus-eth1-mainnet-master-"${BENCHMARKING_TYPE}"-benchmark.service)
+
+  echo "SYSTEMD_INVOCATION_ID for this service run is: ${SYSTEMD_INVOCATION_ID}"
+
+  # generate log file for previous run
+  echo "journalctl _SYSTEMD_INVOCATION_ID=${SYSTEMD_INVOCATION_ID} -q --no-hostname >>${BENCHMARK_DESTINATION}/${BENCHMARKING_SERVICE_LOG_FILE_NAME}"
+  journalctl _SYSTEMD_INVOCATION_ID="${SYSTEMD_INVOCATION_ID}" -q --no-hostname >>"${BENCHMARK_DESTINATION}/${BENCHMARKING_SERVICE_LOG_FILE_NAME}"
 }
 
 function generateBenchmarkSummary() {
   touch "${ENVIRONMENT_LOG_FILE_PATH}"
-   {
-        fetchHostInformation
-        fetchBenchmarkingJobSummary
-        compareBenchmarkWithPrevious
-   } >> "${ENVIRONMENT_LOG_FILE_PATH}" 2>&1
+  {
+    fetchHostInformation
+    fetchBenchmarkingJobSummary
+    compareBenchmarkWithPrevious
+  } >>"${ENVIRONMENT_LOG_FILE_PATH}" 2>&1
 
-   moveServiceLogToRepo
+  moveServiceLogToRepo
 }
 
 function pushChangesToRepo() {
   cd "${BENCHMARK_DESTINATION}"
   git add .
-  git commit -m "{{ nimbus_eth1_benchmark_publish_commit_message }}" > /dev/null 2>&1
-  git push > /dev/null 2>&1
+  git commit -m "{{ nimbus_eth1_benchmark_publish_commit_message }}"
+  git push
 }
 
 moveBenchmarkingFileToRepo
 generateBenchmarkSummary
 pushChangesToRepo
-
-
